server:
  port: 8089
spring:
  application:
    name: testPayment
  datasource:
    url: jdbc:h2:./db/payment_system;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: root
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
token:
  signing:
    key: ${KEY}
